# Generated by Django 4.1.7 on 2024-03-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0002_comment_video_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('access', models.TextField(choices=[('Доступно всем', 'Доступно всем'), ('Доступно только мне', 'Доступно только мне'), ('Доступно по ссылке', 'Доступно по ссылке')], verbose_name='Права доступа')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videohost.profile', verbose_name='Создатель')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videohost.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Плейлисты',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ['created_at'],
            },
        ),
    ]
