# Generated by Django 4.1.7 on 2024-03-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0003_alter_comment_options_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='videohost.playlist', verbose_name='Плейлист'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_playlist', to='videohost.video', verbose_name='Видео'),
        ),
    ]
