# Generated by Django 4.1.7 on 2024-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0004_video_playlist_alter_playlist_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
