# Generated by Django 4.1.7 on 2024-03-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0005_alter_video_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='videohost.profile', verbose_name='Канал')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='videohost.profile', verbose_name='Подписчик')),
            ],
            options={
                'unique_together': {('subscriber', 'channel')},
            },
        ),
    ]
