# Generated by Django 4.1.7 on 2024-03-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0006_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='channel',
        ),
    ]
