# Generated by Django 4.1.7 on 2024-03-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0007_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videohost.profile', verbose_name='Автор'),
        ),
    ]
