# Generated by Django 4.1.7 on 2024-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0008_alter_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
    ]
