# Generated by Django 4.1.7 on 2024-03-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0010_alter_video_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='videohost.profile', verbose_name='Канал'),
            preserve_default=False,
        ),
    ]
