# Generated by Django 4.1.7 on 2024-03-26 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videohost', '0013_alter_subscription_options_viewshistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewsHistory',
            new_name='ViewHistory',
        ),
    ]
