# Generated by Django 4.1.7 on 2024-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0014_rename_viewshistory_viewhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/avatar/%Y/%m/%d/', verbose_name='Обложка канала'),
        ),
    ]
